name: Notify Main Repository

on:
  push:
    branches:
      - dev

jobs:
  notify-main:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger main repository update
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.BOT_PAT }}
          repository: elytra-tqs/elytra
          event-type: submodule-updated
          client-payload: |
            {
              "submodule_name": "stations-management",
              "commit_sha": "${{ github.sha }}",
              "branch": "dev"
            }